name: Git LFS fetch test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
        clean: true
        ssh-key: ${{secrets.sshkey}} 
    - run: git lfs pull
