name: Git LFS fetch test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false
        clean: true
        ssh-key: ${{secrets.sshkey}}
    - run: git config --local --unset-all http.https://github.com/.extraheader
    - run: git lfs fetch --all
